FROM mongo:4.0

VOLUME /data
EXPOSE 27001 27002 27003

COPY docker-mongo-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-mongo-entrypoint.sh

ENTRYPOINT ["docker-mongo-entrypoint.sh"]